name = ""
license = "MIT"
licenselink = "https://github.com/razonyang/hugo-mod-____/blob/main/LICENSE"
description = ""
homepage = "https://example.com/"
tags = []
features = []
min_version = "0.97.0"

[author]
  name = ""
  homepage = ""
